#cloud-config
hostname : kube-rancher-01
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC72ojJ7+r3HzPtbq1CGuVERC0qeDwASwBlr88pX3odP/ffqQrnJsBksDYHyYLATZUhPWUOtP3F9AbBXWqkW0WNQ7nL90Ac/N3gMZY19WvYEE8In53DrJn0R4zAEYUv1JgFY7tTSqk9dMIK1GEEb/uR1kcBSUy9puTo6Dnz2n3kZGjj8SOIabKJwQUmQn7+uKmy7yF4drdyhNQnrdjW4PmnGxoaPdaaFRTRBkSlEk278vqZDfVXGz1A/5WIwris0JmYuV4Rbzbf3tzbxLoSbwbEKDv88Tm23/iWGZjkeMT+SbLy/wb+Vv1/ITKEZzDtrwLVS7++kjgua1sZt1xpodBl wisma@DESKTOP-GRFMUGQ
#users:
#  - name: docker
#    ssh_authorized_keys:
#      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC72ojJ7+r3HzPtbq1CGuVERC0qeDwASwBlr88pX3odP/ffqQrnJsBksDYHyYLATZUhPWUOtP3F9AbBXWqkW0WNQ7nL90Ac/N3gMZY19WvYEE8In53DrJn0R4zAEYUv1JgFY7tTSqk9dMIK1GEEb/uR1kcBSUy9puTo6Dnz2n3kZGjj8SOIabKJwQUmQn7+uKmy7yF4drdyhNQnrdjW4PmnGxoaPdaaFRTRBkSlEk278vqZDfVXGz1A/5WIwris0JmYuV4Rbzbf3tzbxLoSbwbEKDv88Tm23/iWGZjkeMT+SbLy/wb+Vv1/ITKEZzDtrwLVS7++kjgua1sZt1xpodBl wisma@DESKTOP-GRFMUGQ
rancher:
  console: centos
  network:
    interfaces:
      eth0:
#        address: 192.168.0.200/24
#        gateway: 192.168.0.150
#        mtu: 1500
        dhcp: true
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4